modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="allofitmod"
version="1.0.0"
displayName="All-Of-It Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ImMadMax And SirLanceathott, MCreator"

[[dependencies.allofitmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



