modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="testagain"
version="1.0.0"
displayName="testagain"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Max, MCreator"

[[dependencies.testagain]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



